with-expecter: False
dir: tests/mocks
all: True
outpkg: mocks
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
packages:
  car-services-api.totote05.ar/domain/adapters:
    # config:
    #   recursive: True