name: tests
on:
  pull_request:
    branches:
      - master
      - develop
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup go version 1.21.4
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.4
      - name: Installing dependencies
        run: go get .
      - name: Run tests
        run: ./run_tests.sh